version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: concert_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: concert_platform
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/concert_platform
      JWT_SECRET: super_secret_key
    depends_on:
      - postgres
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: concert_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    depends_on:
      - rabbitmq

  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/concert_platform?sslmode=disable
    depends_on:
    - postgres

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - chat-service  
  
  concert-service:
    build: ./concert-service
    container_name: concert-service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/concert_platform?sslmode=disable
      JWT_SECRET: supersecret
    depends_on:
      - postgres
    